CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  default_currency CHAR(3) NOT NULL DEFAULT 'INR',
  timezone VARCHAR(100) NOT NULL DEFAULT 'Asia/Kolkata',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS expenses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  client_id VARCHAR(120) NOT NULL,
  amount NUMERIC(14, 2) NOT NULL CHECK (amount > 0),
  currency CHAR(3) NOT NULL DEFAULT 'INR',
  transaction_type VARCHAR(10) NOT NULL CHECK (transaction_type IN ('spent', 'received')),
  category_id UUID,
  category VARCHAR(100),
  sub_category VARCHAR(100),
  merchant VARCHAR(150),
  payment_method VARCHAR(50),
  date DATE NOT NULL,
  reminder_date DATE,
  note TEXT,
  is_recurring BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, client_id)
);

CREATE INDEX IF NOT EXISTS expenses_user_date_idx ON expenses(user_id, date DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS expenses_user_updated_idx ON expenses(user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS ai_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  description TEXT NOT NULL,
  transaction_type TEXT NOT NULL,
  predicted_category TEXT NOT NULL,
  predicted_class_index INTEGER,
  confidence REAL,
  final_category TEXT NOT NULL,
  final_class_index INTEGER,
  was_correct INTEGER NOT NULL CHECK (was_correct IN (0, 1)),
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS ai_feedback_user_created_idx ON ai_feedback(user_id, created_at DESC);
